export const IPC = {
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSE: 'window:close',
  WINDOW_IS_MAXIMIZED: 'window:isMaximized',
  SC_ME: 'sc:me',
  SC_LIKES: 'sc:likes',
  SC_STREAM_URL: 'sc:streamUrl',
  SC_SEARCH: 'sc:search',
  SC_PLAYLISTS: 'sc:playlists',
  SC_LIKED_PLAYLISTS: 'sc:likedPlaylists',
  SC_LIKE_PLAYLIST: 'sc:likePlaylist',
  SC_PLAYLIST: 'sc:playlist',
  SC_FEED: 'sc:feed',
  SC_USER: 'sc:user',
  SC_USER_TRACKS: 'sc:userTracks',
  SC_USER_PLAYLISTS: 'sc:userPlaylists',
  SC_USER_LIKES: 'sc:userLikes',
  SC_HOME: 'sc:home',
  SC_PLAY_HISTORY: 'sc:playHistory',
  SC_TRACKS_BY_IDS: 'sc:tracksByIds',
  SC_GENRE_TRACKS: 'sc:genreTracks',
  SC_TRACK: 'sc:trackDetail',
  SC_TRACK_RELATED: 'sc:trackRelated',
  SC_TRACK_COMMENTS: 'sc:trackComments',
  SC_TRACK_LIKERS: 'sc:trackLikers',
  SC_LIKE_TRACK: 'sc:likeTrack',
  SC_REPOST_TRACK: 'sc:repostTrack',
  SC_FOLLOW_USER: 'sc:followUser',
  SC_FOLLOWING_IDS: 'sc:followingIds',
  SC_LIKED_TRACK_IDS: 'sc:likedTrackIds',
  SC_REPOSTED_TRACK_IDS: 'sc:repostedTrackIds',
  SC_NOTIFICATIONS: 'sc:notifications',
  AUTH_LOGOUT: 'auth:logout',
  OPEN_EXTERNAL: 'app:openExternal',
  COVER_BYTES: 'app:coverBytes',
  SC_WAVEFORM: 'sc:waveform',
  PLAYER_PROGRESS: 'player:progress',
  PLAYER_COMMAND: 'player:command',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
} as const

export type PlayerCommand = 'toggle' | 'next' | 'previous'
